### ISSUE TITLE
tgeogpoint?

### ISSUE THREAD

**Issue by wendellwt** [adonmo/mobilitydb-sqlalchemy#6]
Does mobilitydb-sqlalchemy operate on TGeogPoint?  Doesn't TGeomPoint use planar geometries for calculations (distance, etc.) whereas TGeogPoint uses spherical geometries for those calculations?  Does that distinction make a difference to sqlalchemy?

Thanks,
Wendell

**Comment by chaitan94** [comment]
Right now TGeogPoint hasn't been implemented yet. But it should be straightforward as implementing it would be very similar to TGeomPoint. I will be adding it soon.

**Comment by chaitan94** [comment]
TGeogPoint is now supported in 0.2.1 release.
